detect_ball:
  ros__parameters:
    # tuning_mode: false # Could set this here but leave it off so it can be easily set by the launch script
    x_min: 0
    x_max: 100
    y_min: 0
    y_max: 100
    h_min: 31
    h_max: 75
    s_min: 82
    s_max: 225
    v_min: 22
    v_max: 239
    sz_min: 0
    sz_max: 100

detect_ball_3d:
  ros__parameters:
    h_fov: 1.089
    ball_radius: 0.033
    camera_frame: "camera_link_optical"

follow_ball:
  ros__parameters:
    rcv_timeout_secs: 0.5
    angular_chase_multiplier: 0.4
    forward_chase_speed: 0.4
    search_angular_speed: 0.8
    max_size_thresh: 0.1
    filter_value: 0.9
